# For documentation, see https://golangci-lint.run/usage/configuration/

run:
  build-tags:
    - seccomp

linters:
  enable:
    - gofumpt
    - gosec
    - errorlint
    - unconvert

linters-settings:
  gosec:
    confidence: medium
    severity: medium
