# For documentation, see https://golangci-lint.run/usage/configuration/

run:
  build-tags:
    - seccomp

linters:
  enable:
    - gofumpt
    - errorlint
    - unconvert
    - unparam
    - stylecheck

linters-settings:
  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: ["all", "-ST1003", "-ST1016"]
