# For documentation, see https://golangci-lint.run/usage/configuration/

run:
  build-tags:
    - seccomp

# all available settings of specific linters
linters-settings:
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/opencontainers/runc

linters:
  enable:
    - gofmt
    - goimports
