# For documentation, see https://golangci-lint.run/usage/configuration/

run:
  build-tags:
    - seccomp

linters:
  enable:
    - gofumpt
    - errorlint
    - revive
    - unconvert
    - unparam

issues:
  include:
    - EXC0002
