# NOTE Github Actions execution environments lack a terminal, needed for
# some integration tests. Two ways to get a terminal are used below:
#
# 1. script utility -- for "local" integration tests;
# 2. ssh -tt -- for Vagrant VMs (script is buggy on CentOS 7).

name: ci
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  # kernel 3.10 (frankenized), systemd 219
  centos7:
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - name: "Cache ~/.vagrant.d/boxes, using hash of Vagrantfile.centos7"
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-${{ hashFiles('Vagrantfile.centos7') }}

      - name: prepare vagrant
        run: |
          ln -sf Vagrantfile.centos7 Vagrantfile
          vagrant up
          vagrant ssh-config >> ~/.ssh/config

      - name: system info
        run: ssh default 'rpm -q centos-release kernel systemd'

      - name: unit tests
        run: ssh default 'sudo -i make -C /vagrant localunittest'

      - name: integration tests (fs cgroup driver)
        run: ssh -tt default "sudo -i make -C /vagrant localintegration"

      - name: integration tests (systemd cgroup driver)
        run: ssh -tt default "sudo -i make -C /vagrant localintegration RUNC_USE_SYSTEMD=1"

      - name: rootless integration
      # FIXME: rootless is skipped because of EPERM on writing cgroup.procs
        if: false
        run: ssh default "sudo -i make -C /vagrant localrootlessintegration"
