# NOTE Github Actions execution environments lack a terminal, needed for
# some integration tests. Two ways to get a terminal are used below:
#
# 1. script utility -- for "local" integration tests;
# 2. ssh -tt -- for Vagrant VMs (script is buggy on CentOS 7).

name: ci
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  # cgroup v2 unified hierarchy + very recent kernel (openat2)
  fedora:
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: prepare vagrant
        run: |
          ln -sf Vagrantfile.fedora33 Vagrantfile
          # Retry if it fails (download.fedoraproject.org returns 404 sometimes)
          vagrant up || vagrant up
          vagrant ssh-config >> ~/.ssh/config

      - name: system info
        run: ssh default 'sh -exc "uname -a && systemctl --version && df -T && criu --version"'

      - name: unit tests
        run: ssh default 'cd /vagrant && sudo make localunittest'

      - name: cgroupv2 with systemd
        run: ssh -tt default "sudo make -C /vagrant localintegration RUNC_USE_SYSTEMD=yes"

      - name: cgroupv2 with fs2
        run: ssh -tt default "sudo make -C /vagrant localintegration"

      - name: cgroupv2 with systemd (rootless)
        run: ssh -tt default "sudo make -C /vagrant localrootlessintegration RUNC_USE_SYSTEMD=yes"

      - name: cgroupv2 with fs2 (rootless)
        run: ssh -tt default "sudo make -C /vagrant localrootlessintegration"


  # kernel 3.10 (frankenized), systemd 219
  centos7:
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: prepare vagrant
        run: |
          ln -sf Vagrantfile.centos7 Vagrantfile
          vagrant up
          vagrant ssh-config >> ~/.ssh/config

      - name: system info
        run: ssh default 'rpm -q centos-release kernel systemd criu'

      - name: unit tests
        run: ssh default 'sudo -i make -C /vagrant localunittest'

      - name: integration tests (fs cgroup driver)
        run: ssh -tt default "sudo -i make -C /vagrant localintegration"

      - name: integration tests (systemd cgroup driver)
        run: ssh -tt default "sudo -i make -C /vagrant localintegration RUNC_USE_SYSTEMD=1"

      - name: rootless integration
      # FIXME: rootless is skipped because of EPERM on writing cgroup.procs
        if: false
        run: ssh default "sudo -i make -C /vagrant localrootlessintegration"
